### ISSUE TITLE
Unmatching security certificate

### ISSUE THREAD

**Issue by Tusker13-04** [JackBiggin/jacklyn.dev#3]
certificate was issued for a different web address than the one it is being used for, http is uses instead of https
So, chrome has marked the website dangerous and vulnerable to attackers 
![Screenshot_20210511_102513](https://user-images.githubusercontent.com/63436014/117761636-55fc0780-b245-11eb-867e-ce7d4554238d.png)

**Comment by JackBiggin** [comment]
Apologies for the incredibly slow reply, but this has been fixed!
